[File "CONFIG.CMD".  Since bootstrap files are not standardized, this
file is presented using a pseudo configuration file syntax.]

load root server list             from file ROOT.SERVERS
load zone SRI.COM.                from file SRI.ZONE
load zone CSL.SRI.COM.            from file CSL.ZONE
load zone ISTC.SRI.COM.           from file ISTC.ZONE
load zone 18.128.IN-ADDR.ARPA.    from file SRINET.ZONE
load zone 33.12.192.IN-ADDR.ARPA. from file SRI-CSL-NET.ZONE
